[".config/alacritty/dracula.yml"]
    type = "file"
    url = "https://raw.githubusercontent.com/dracula/alacritty/master/dracula.yml"
    refreshPeriod = "168h"
        
# ".vim/pack/alker0/chezmoi.vim"]
#     type = "git-repo"
#     url = "https://github.com/alker0/chezmoi.vim.git"
#     refreshPeriod = "168h"

[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    clone.args = ["--depth=1"]
    refreshPeriod = "168h"

["Library/Keyboard Layouts/Colemak DH.bundle"]
    type = "file"
    url = "https://github.com/ColemakMods/mod-dh/archive/refs/heads/master.tar.gz"
    ["Library/Keyboard Layouts/Colemak DH.bundle".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mod-dh-master/macOS/Colemak DH.bundle"]
    